		<section>
		<section>
		<h3>  Conclusions </h3>	
		<ul class = "fragment" 	data-fragment-index="1" align="left">
		<li class = "fragment" 	data-fragment-index="2" align="left"> Devised SHS Model of CT in Desert Ant   </li>
		<li class = "fragment" 	data-fragment-index="3" align="left"> Formulated stochastic controller for multi-boundary coverage </li> 
		<li  class = "fragment" data-fragment-index="4" align="left"> Investigated the properties of communication network generated by SCS</li>
		<li  class = "fragment" data-fragment-index="5" align="left"> <div style="color:blue"> Explored challenges of multi-robot simulation with communication </div>
		</li>
		</ul>
		</section>


		<section>
		<h3> ACS Lab </h3>	
		<img src="Figs/ACSLab.jpg"  height="400" width="800" />

	
		</section>
		</section>
