	<section>
					<section>
					<h3>Novel Contributions</h3>
						<b> Devised Stochastic Hybrid System (SHS) model of CT in <i>A. Cockerelli</i> </b>
						<p>  <small> <b> Source: <a href="https://goo.gl/SqG93d"> Kumar et al., HSCC '13</a> </b>  </small> </p> 
						<p> <div style="color:blue;"> <b> My contributions </b></p>
						 	
						   <ul> <li> Devised CRN <li> Derived moments of SHS <li> Helped validate parameter estimation </ul>   
						</div> 

						<img src="Figs/sideview_white.jpg"  height="100" width="300" style="position:absolute; BOTTOM:-200px; RIGHT:300px;"/>	
					</section>

					
					<section>
					<h3>Novel Contributions</h3>
					<b> Formulated stochastic controller for Multi-Boundary Coverage </b>
						<p>
						<small> <b> Sources: </b> <a href="http://goo.gl/5pCqCg"> <b> Pavlic et al., <i> ISRR '13</i> </b> </a>; <a href="https://goo.gl/DFligW"> <b> Pavlic et al., <i> SME '14 </i> </b> </a>;<a href="https://goo.gl/DbbUC1"> <b> Wilson et al., <i> Swarm Int '14 </i> </b> </a>  </small>
						</p>
						<p> <div style="color:blue;"> <b> My contributions </b></p>
						 	
						   <ul> <li> Devised a closed-form solution to bimolecular CRN <li> Analyzed the unimolecular approximation to CRN </ul>   
						</div> 
						<img src="Figs/RoboZyme_thinks.png"  height="100" width="300" style="position:absolute; BOTTOM:-200px; RIGHT:300px;"/>	
						
					</section> 

					<section>
					$$ 
					\newcommand{\Poly}{\mathcal{P}}
					\newcommand{\G} {\mathcal{G}}
					\newcommand{\pcon}{p_{\mathsf{con}}}
					$$
					
					<h3>Novel Contributions</h3>
					<b> Analyzed Communication Graph $\G$ on Boundary  </b>
						<ul>
							<li> Computed connectivity probability $\pcon(\G)$ and spatial statistics for uniform coverage  </li>
								<p> <small> <a href="https://goo.gl/z2OhbC" > Kumar and Berman, <i> ICRA '14 </i> </a>  </small>  </p>
							<li>  Spatial statistics over connected communication graphs </li>
								<p> <small> Kumar and Berman, <i> IEEE-TRO (under review) </i>  </small>  </p>	
								
							<li> Non-uniform SCS, Non-iid SCS, Finite Robots </li>
								<p> <small> Kumar and Berman, <i> SICOMP (in prep.) </i>  </small>  </p>
	
						</ul>
				 
						<figure style="position:absolute; TOP: 300px; RIGHT:-200px;">
						<img src="Figs/config.svg"  height="75" width="400" />

						</figure>
					</section>

					<section>
					<h3>Agenda</h3>
					
						<ul>
							<!--<li> Study of CT in Desert Ant 
							<li> Formulating Stochastic Control policies for multi-boundary coverage -->								
							<li> Analyzing properties of communication network generated by SCS
							<li> Challenges in integrating Multi-Robot  simulation with wireless communications 
	
						</ul>
				 
						
					</section>

					<section>
					<h3> Challenges </h3>
					<b> Extracting a theory  from MC Simulations </b> 	
					<ul>
							<!--<li> Study of CT in Desert Ant 
							<li> Formulating Stochastic Control policies for multi-boundary coverage -->								
							<li> MC algorithms easy to simulate, but hard to reason about 
							<li> Lack of a general theory for simulations
							<li> Which generalizations were easy / hard?
	
						</ul>

					</section>

						<section>
					<h3> Outcome </h3>
					<b> Comprehensive framework after about 3 years </b> 	
					<ul>
							<!--<li> Study of CT in Desert Ant 
							<li> Formulating Stochastic Control policies for multi-boundary coverage -->								
							<li> Bulk of my dissertation
							<li> Draws from multiple disciplines : Computational Geometry, Random Graphs, Order Statistics 
							<li> Hardness results based on Counting Complexity 
	
						</ul>

					</section>
						
						
					
				</section> 	

