

<section>

<section>
<h3> Analyzing the Wireless Network of an SCS</h3>



<table>
<tr class = "noBorder">
	<td>	
	<figure>
	<img src="Figs/Ganesh.png"  height="150" width="125"/>	

	</figure>
	</td>



<td>	
	<figure>
	<img src="Figs/Spring.png"  height="150" width="125"/>	

	</figure>
	</td>
</tr>
</table>

<small> <b> Sources <br>
<ul> <li> <a href="https://goo.gl/z2OhbC" >(Kumar and Berman 2014) </a> <li>  (Kumar and Berman, TRO [under review]) <li> (Kumar and Berman [in prep for SICOMP])   </ul> </b> </small>

 <figure>
	<img src="bcover-conn/Figs/sensornet.jpeg"  height="150" width="200" style="position:absolute;TOP: -100px; RIGHT:-300px;" />
</figure>


 <figure>
	<img src="bcover-conn/Figs/commnet.jpeg"  height="150" width="200" style="position:absolute;BOTTOM: -100px; LEFT:-200px;" />
</figure>
</section>


<section> 
<h3> Motivation</h3>
<b> Analyzing the spatial distributions generated by SCS </b>


<ul>
<li> How many robots on average does it take to fill a disk boundary? 
<li> What happens if robot concentrations are non-uniform?
<li> What if robots have different sizes?
</ul>



<figure style="float:top;">
<img src="bcover-multi/Figs/RoboZyme_problem_cartoon.png"  height="200" width="250" style="position:absolute; BOTTOM:-50px; RIGHT:-250px;"/>
</figure>



</section>

<section> 
<h3> Motivation</h3>
<b> Setting up a connected Wireless network around a boundary </b>

<table>
<tr class="noBorder">
<td>
<img src="bcover-conn/Figs/Robot-circles.png"  height="200" width="200" style="border:none;"/>
</td>

<td style="vertical-align:top;">
<p align ="justify">
Robots of communication/sensing radii $d$ and diameter $R$  attach using SCS.
<ul>
<li> What is the probability that they form a connected network?
<li> How many robots ensure $95\%$ chance of connectivity? 
</ul>
</td>
</tr>
</table>


</section>

<section> 
<h3> Motivation</h3>
<b> Handling noise in Deterministic Coverage Schemes </b>

<p align="justify">
Robots attach at equidistant positions, but have odometric noise.

<table width="1200px">
<tr class="noBorder">
<td style="vertical-align:top">
<ul>
<li> What guarantees can we give about connectivity?
<li> What can we say about robot pdfs?
<div style="color:red"> Complicated mixture of Gaussians! </div>
<li> What happens for robots with different noise profiles?
<div style="color:red"> PDFs still harder to compute!  </div>  
</ul>
</td>
<td>
<figure style="float:top;">
<img src="bcover-conn/Figs/Gaussians.png"   style="border:none; height:650; width:650;"/>
</figure>
</td>
</tr>
</table>


</section>


<section> 
$$
\newcommand{\nor}{n}
\newcommand{\conn}{d}
\newcommand{\dia}{R}
$$

<h3> Objectives </h3>
<p align="left">
 Given the coverage scheme, robot details ($\dia,\conn$), and the boundary. Provide the designer with tools to: 
</p>
<ul class="fragment" data-fragment-index="1">
<li class="fragment" data-fragment-index="2"> Compute the probability of connectivity of the communication network. 
<li class="fragment" data-fragment-index="2"> Compute spatial pdfs and inter-robot distances.
<li class="fragment" data-fragment-index="3"> Design the number of robots $\nor$ and communication range $\conn$ to satisfy a given connectivity probability.
</ul>

<img src="bcover-conn/Figs/PheenoCap.png"   style="border:none; height:350; width:350;position:absolute;bottom:-300px;right:50px;"/>
</section>



<section>
$$
\newcommand{\Bo}{\mathcal{B}}
\newcommand{\conn}{d}
\newcommand{\Rob}[1]{\mathcal{R}_{#1}}
\newcommand{\dia}{R}
\newcommand{\upos}[1]{x'_{#1}}
\newcommand{\uposvec}{\mathbf{x}'}
\newcommand{\rvupos}[1]{X'_{#1}}
\newcommand{\rvuposvec}{\mathbf{X}}
$$

<h3> Problem Setting</h3>


<p  class="fragment" 	data-fragment-index="1">
<ul>
<li> Similar to multi-boundary coverage, except we have only one line segment boundary $\mathcal{B}$
<li> $\mathcal{B}$ has one end coloured  
<li>  Robots attach to $\Bo$ using a programmed SCS 
<div style="color:blue"> Could be just a DCS + noise  </div>  


</ul>

<figure>
<img src="bcover-conn/Figs/Env.png"   style="border:none; height:650; width:750;"/>	
</figure>
</p>

</section>



<section>
<h3> Robot Capabilities </h3>


<ul>
<li> Sense and communicate within $\conn$
<li> Detect coloured endpoint of $\Bo$   
<li> Know id of self and others
<li> Measure distances on $\Bo$ using odometry 
</ul>

<figure>
<img src="bcover-conn/Figs/Env.png"   style="border:none; height:650; width:750;"/>	
</figure>
</section>



<section> 

<h3> Robot Configuration </h3>

<p>
<ul>
<li> Boundary has length $s$ measured by odometry
<li> Position of $\Rob{i}$ = distance of left end from coloured endpoint = $\upos{i}$ on $\Bo$
<li> Configuration = <i>unordered</i> positions $\uposvec = \upos{1:n}$ 
<li> Configuration is <it>collision-free (CF) </it> iff $|\upos{i} - \upos{j}| \geq \delta$
</ul>
</p>


<figure>
<img src="bcover-conn/Figs/Att1.png"   style="border:none; height:800; width:1000;"/>	
<figcaption> <small> <b>  $\Rob{2}$ and $\Rob{4}$ collide (red circles), with unordered positions $\upos{1:4}$</b> </small> </figcaption> 
</figure>
</section>



<section>

<h3> Robot communication</h3>

$\Rob{i}$ and $\Rob{j}$ communicate iff $|\upos{i} - \upos{j} |  \leq \conn$


<figure>
<img src="bcover-conn/Figs/Att1.png"   style="border:none; height:800; width:1000;"/>	
<figcaption> <small> <b>  Pairs $\Rob{1},\Rob{3}$ and $\Rob{2},\Rob{4}$ communicate (green dotted lines)</b> </small> </figcaption> 
</figure>

</section>




<section>
<h3> Communication Graph $\mathcal{G}$ </h3>

<p class="fragment" 	data-fragment-index="1" align="left">
Define the communication graph $\mathcal{G}$ as one with
<ul class="fragment" 	data-fragment-index="1" align="left">
<li class="fragment" 	data-fragment-index="1"> vertices at each position $\upos{i}$ 
<li class="fragment" 	data-fragment-index="1"> edges connecting pairs of inter-communicating robots
</ul>
</p>

<p class="fragment" 	data-fragment-index="2" align="left">For theoretical convenience, assume $\Rob{0}=-\dia$ and $\Rob{n+1}=s$ attach at endpoints of $\Bo$.

<figure class="fragment" 	data-fragment-index="3">
<img src="bcover-conn/Figs/Att2.png"   style="border:none; height:800; width:1000;"/>	
<figcaption> <small> <b>  Connected $\G$ formed by 3 robots and 2 artificial ones. </b> </small> </figcaption> 
</figure>

</section>

<section>
<h3> Communication Graph $\mathcal{G}$ </h3>

Several connected communication graphs are possible:
\begin{align}
\G&=\{(0,1),(1,3),(2,3),(2,4)\} \\
\G&=\{(0,1),(1,3),(1,2),(2,3),(3,4)\}.
\end{align}


<figure style="float:top;" >
<img src="bcover-conn/Figs/Att2.png"   style="border:none; height:800; width:1000;position:absolute; BOTTOM:-150px; RIGHT:250px;"/>	
<figcaption> <small> <b>  </b> </small> </figcaption> 
</figure>

</section>



<section>
$$
\newcommand{\pos}[1]{{x}_{#1}}
\newcommand{\posvec}{\mathbf{x}}
\newcommand{\rvpos}[1]{{X}_{#1}}
\newcommand{\rvposvec}{\mathbf{X}}
\newcommand{\rvuposvec}{\mathbf{X}'}
\newcommand{\si}[1]{s_{#1}}
\newcommand{\rvsla}[1]{S_{#1}}
\newcommand{\svec} {\mathbf{s}}
\newcommand{\fpar}[1]{h_{#1}}
$$
<h3> Order Statistics </h3>

<ul>  <b> Order Statistics :</b> Sorted positions $\posvec = \pos{1:n}$ <a href="https://goo.gl/4nzdyK"> (David'03) </a>
<li>  $\uposvec$ is called <i> parent </i> of $\posvec$  
<li>  Each $\upos{i}$ samples a r.v $\rvupos{i}$ with <i>parent pdf</i> $\fpar{i}$ suppoted on $\Bo$
<li>  Joint pdf of $\rvuposvec$ specifies the SCS   
</ul>
</p>

<figure>
<img src="bcover-conn/Figs/Att3.png"   style="border:none; height:800; width:1000;position:absolute; BOTTOM:-150px; RIGHT:250px;"/>	
<figcaption> <small> <b> Order statistics given by $\posvec:=\pos{1..3}$ </b> </small> </figcaption> 
</figure>

</section>

<section>
<h3> Slacks </h3>

<ul  align="left"> 
<li  align="left"> <b> Slacks </b> are interrobot distances $\si{i} :=\pos{i} - \pos{i-1}$
<li  align="left"> <b> Slack vector </b> $\svec := \si{1:n+1}$
<li  align="left"> CF requires $\si{i} \geq \dia$

<li  align="left"> Connectivity requires $\si{i} \leq \conn$
<li  align="left"> Slack samples the rv $\rvsla{i}$ realized by $\rvuposvec$
 </ul>

<br> <br>
<figure>
<img src="bcover-conn/Figs/Att3.png"   style="border:none; height:800; width:1000;position:relative"/>	
<figcaption "style=position:absolute;bottom:0;top:0;left:0;right:0"> <small> <b> Slacks given by $\svec:=\si{1..4}$ </b> </small> </figcaption> 
</figure>

</p>



</section>






<section>
$$
\newcommand{\upos}[1]{x_{#1}}
\newcommand{\rvupos}[1] {X_{#1}}
\newcommand{\rvuposvec}{\mathbf{X}}
\newcommand{\fpar}{h}
\newcommand{\Fpar}{H}
\newcommand{\rvsi}[1] {S_{#1}}
$$
<h3> Problem Statement - I</h3>

<p  align="left">Suppose $\upos{i}$ are realizations of iid parents $\rvupos{i}$ each with pdf $\fpar(t)$ supported on $\Bo=\{t:0\leq t\leq s\}$. 
<p  align="left"> Determine:

<ul  	data-fragment-index="1" align="left"> 
<li  	data-fragment-index="1" align="left"> Probability $\pcon$ that $\G$ is connected.
<li  	data-fragment-index="1" align="left"> PDFs of order statistics and slacks.
</ul> 


</section>

<section>

<h3> Problem Statement - II</h3>

<p 	data-fragment-index="1" align="left">Extend the analysis in Part I to the cases when: 
<p  	data-fragment-index="1" align="left"> 

<ul 	data-fragment-index="1" align="left"> 
<li 	data-fragment-index="1" align="left"> robots have distinct communication radii $d_i$ 
<li  	data-fragment-index="1" align="left"> parents $\rvuposvec$ are inid
</ul> 
<p 	data-fragment-index="1" align="left"> Determine the complexity of computing $\pcon$. 


<figure style="float:top;">
<img src="bcover-conn/Figs/Gaussians.png"   style="border:none; height:250px; width:300px;"/>
<figcaption "style=position:absolute;bottom:0;top:0;left:0;right:0"> <small> <b> INID Gaussian parents </b> </small> </figcaption> 
</figure>

</section>


					
</section> <!-- problem setting -->


<section>

<section>
<h3> Problem Solving Tools</h3>



<ul  	data-fragment-index="1" align="left">
<li  	data-fragment-index="2"> Geometric interpretation of $\posvec$ and $\svec$ 
<li class="fragment" data-fragment-index="3"> Order Statistics  
<li class="fragment" data-fragment-index="4"> Polytopes  
<li class="fragment" data-fragment-index="5"> Complexity of simplex/hypercube intersection   

</ul>

</section>

<section>
<h3> Communication Graph $\mathcal{G}$ </h3>

<ul class="fragment" 	data-fragment-index="1" align="left">
<li class="fragment" 	data-fragment-index="2"> $\G$ is a <i> Geometric Graph </i>
<li class="fragment" data-fragment-index="3"> When $\upos{i}$ are drawn from iid rv's, $G$ is a<i> Random Geometric Graph (RGG) </i>  <a href="https://goo.gl/LGVqWr"> (Penrose '03)</a>
<li class="fragment" data-fragment-index="4"> $\G$ is  <i>Gilbert's Disk Graph </i> <a href="https://goo.gl/LxWbzh" > (Haenggi '12)</a> in $\mathbb{R}^1$ 

</ul>

</section>



<section>
<h3> Position Simplex </h3>
$$
\newcommand{R}{\mathbb{R}}
\newcommand{\psimp}{\mathcal{P}}
$$

<p ul class="fragment" 	data-fragment-index="1" align="left"> Consider <i>point</i> robots, for which CF is irrelevant </p>

<ul class="fragment" 	data-fragment-index="1" align="left">
<li class="fragment" 	data-fragment-index="2"> Think of $\posvec$ (and $\uposvec$) as a point in $\R^n$
<li class="fragment" data-fragment-index="3"> Valid (sorted) positions have 
$$
\pos{0} = 0\leq \pos{1} \leq \ldots \pos{n} \leq \pos{n+1} =s
$$

<li class="fragment" data-fragment-index="4"> Set of such positions forms <i> position simplex </i> $\psimp$  
<li class="fragment" data-fragment-index="5"> Vertices of $\psimp$ are of the form $$(0,0,\ldots,0,s,s,\ldots,s)$$   

</ul>

</section>

<section>
<h3> Slack Simplex </h3>
$$
\newcommand{\ssimp}{\mathcal{S}}
\newcommand{\1}{\mathbf{1}}
$$

<ul class="fragment" 	data-fragment-index="1" align="left">
<li class="fragment" 	data-fragment-index="2"> Think of $\svec$ as a point in $\R^{n+1}$
<li class="fragment" data-fragment-index="3"> Valid slack vectors have 
$$
\begin{align}
\si{i} \geq 0 \\
 \sum_{i=1}^{n+1} \si{i} = s, ~\text{or as a half space}~ \sum_{i=1}^{n}  \si{i} \leq s.
\end{align}
$$

<li class="fragment" data-fragment-index="4"> Set of such vectors forms <i> slack simplex </i> $\ssimp$  

</ul>

</section>


<section>
<h3> Defining Connectivity </h3>
$$
\newcommand{\hyp}{\mathcal{hyp}}
\newcommand{\1}{\mathbf{1}}
$$

<ul class="fragment" 	data-fragment-index="1" align="left">
<li class="fragment" 	data-fragment-index="2"> Connected slack vectors have $0 \leq \si{i} \leq \conn$
<li class="fragment" data-fragment-index="3"> All these vectors lie in a hypercube 
$$
\hyp := \{ \svec \in \R^{n+1} : 0\leq \si{i} \leq \conn \}
$$

<li class="fragment" data-fragment-index="4"> This is immaterial of $\svec$ lying in $\ssimp$.  

</ul>

</section>

<section>
<h3> Connected and Disconnected Regions </h3>
$$
\newcommand{\hyp}{\mathcal{H}}
\newcommand{\1}{\mathbf{1}}
\newcommand{\fav}{\mathcal{F}}
\newcommand{\unfav}{\mathcal{U}}
\newcommand{\vvec}{\mathbf{v}}
$$

<ul class="fragment" 	data-fragment-index="1" align="left">
<li class="fragment" 	data-fragment-index="2"> For $\G%$ to be connected, we need $\svec \in \ssimp \cap \hyp$
<li class="fragment" data-fragment-index="3"> Define  the <i> connected region</i> $\fav := \ssimp \cap \hyp$
<li class="fragment" data-fragment-index="4"> Define the <i> disconnected region </i> $\unfav := \ssimp \setminus \fav$ 

</ul>

</section>


<section>
<h3> Decomposing  $\unfav$ </h3>
$$
\newcommand{\hyp}{\mathcal{H}}
\newcommand{\1}{\mathbf{1}}
\newcommand{\fav}{\mathcal{F}}
\newcommand{\unfav}{\mathcal{U}}
\newcommand{\vvec}{\mathbf{v}}
$$

<p align="left" class="fragment" 	data-fragment-index="1"><b> Theorem (<a href="https://goo.gl/B0D4L1"> Kumar and Berman </a>) </b> The disconnected region can be expressed as the intersection of simplices 
$$
\unfav := \bigcap\limits_{\vvec \in \{0,1 \} ^{n+1}, \1^T \vvec \geq 1} \ssimp(\vvec), 
$$

where

$$
\begin{align}
\label{eqn:decomp}
\ssimp(\vvec):= \{ \svec \in \ssimp : s_i \geq \conn ~\text{whenever}~ v_i =1  \}.
\end{align}
$$


<p align="left" class="fragment" 	data-fragment-index="2"> $\ssimp(\vvec)$ forms a simplex of side $s-d\1^T\vvec$.


</section>
</section> <!-- toools -->


<section> <! --- Result summary -->

<section>
<h3> Summary of Results </h3>
</section>

<section>
<h3> Uniform Coverage: Finding $\pcon(\G)$  </h3>
$$
\newcommand{\Vol}{\mathrm{Vol}}
\newcommand{\nmin}{n_{\min}}
$$

<p align="left" class="fragment" 	data-fragment-index="1">
When parents $\rvupos{i}$ are each uniform on $\Bo$, we have  
$$

\pcon(\G) =  1 - \sum _{k=1} ^{\nmin} (-1)^{k-1} \binom{n}{k} {(1-kd/s)^n } ~\text{where}~ \nmin = \lfloor \frac{s}{\conn} \rfloor. 
$$
</p>

<p align="left" class="fragment" 	data-fragment-index="2">
Here, $\nmin$ is the minimum number of robots needed for connectivity.

</p>

</section>

<section>
<h3> IID Coverage: Finding $\pcon(\G)$  </h3>
$$
\newcommand{\rvsvec}{\mathbf{S}}
\newcommand{\jsla}{f_{\rvsvec}(\svec)}
$$

<ul align="left" class="fragment" 	data-fragment-index="1">

<li  class="fragment" 	data-fragment-index="2">
When parents $\rvupos{i}$ are each iid on $\Bo$, we have  
$$
\pcon(\G) =  \frac{\int_{\svec \in \fav} \jsla d\svec }{\int_{\svec \in \ssimp} \jsla d\svec }.
$$

<li class="fragment" 	data-fragment-index="3"> No easy way to do this in general!
<li class="fragment" data-fragment-index="4"> Can be simplified using the probability integral transform $Y'_i := \Fpar_{X'_i}(t)$.

</ul>

</section>

<section>
<h3> IID Coverage: Order Statistics  </h3>


<ul align="left" class="fragment" 	data-fragment-index="1">

<li  class="fragment" 	data-fragment-index="2">
For general $\G$ <a href="https://goo.gl/4nzdyK"> (David &amp; Nagaraja '03) </a>
$$
f_{\rvpos{i}}(t) = \sum \limits_{j=i}^n \Fpar(t)^j (1-\Fpar(t))^{n-j}.
$$


<li class="fragment" 	data-fragment-index="3"> For connected $\G$, we need to marginalize similarly to $\pcon(\G)$.
<li class="fragment" 	data-fragment-index="4"> Formulas for slacks found by a similar process.
</ul>

</section>

<section>
<h3> Finite Robots with IID Coverage  </h3>
$$
\newcommand{\Vol}{\mathrm{Vol}}
\newcommand{\nmin}{n_{\min}}
$$

<p align="left" class="fragment" 	data-fragment-index="1">
When robots have diameter $\dia$, use $\ssimp_{CF}$ instead of $\ssimp$ 
$$
\ssimp_{CF} := \{ \svec \in \ssimp: s_i \geq d  \}.
$$
</p>

<p align="left" class="fragment" 	data-fragment-index="2">
No (simple) formula for any of $\rvpos{i}, S_i$, and $\pcon$! 
</p>


</section>

</section> <!-- Result summary -->


<section> <!-- lower bounds -->
$$
\newcommand{\PCON} {\mathsf{PCON}}
\newcommand{\Q}{\mathbb{Q}}
$$
<section>
<h3> Lower bounds for  $\pcon$ </h3>


<p class="fragment" 	data-fragment-index="1" align ="left">Define the $\PCON(\fpar)$ problem with 


<ul>
<li class="fragment" 	data-fragment-index="2"> <b> Inputs </b>: $(s,d,n) \in \Q_+$ and $\fpar$ is the parent
<li class="fragment" 	data-fragment-index="3"> <b> Output </b>: $\pcon(\G) \in \Q_+$ 
</ul>

</section>



<section>

<h3>  $\PCON(\mathrm{Uni})$ is $\mathrm{Psuedo}-\mathsf{P}$  </h3>


<p class="fragment" 	data-fragment-index="1" align="left" >
<b> Theorem  <a href="" > (Kumar and Berman, to appear) </a></b>  $\PCON(\mathrm{Uni})$ can be solved in $\Omega(n)$ and $O(n \log n)$ time. </b>

<p class="fragment" 	data-fragment-index="2" align="left" >
<b> Proof  </b>: Straightforward from formula.


</section>


<section>
$$
\newcommand{\PH}{\#\mathsf{PH}}
$$

<h3>  $\PCON(\mathrm{poly})$ is $\PH$ </h3>


<p class="fragment" 	data-fragment-index="1" align="left" >
<b> Theorem  <a href="" > (Kumar and Berman, to appear) </a></b>  $\PCON$  is $\PH$ for arbitrary polynomial parents supported on $\Bo$.

<p class="fragment" 	data-fragment-index="2" align="left" >
<b> Proof  </b>: Reduction from <a href="http://goo.gl/nDYL7n" > (Dyer and Frieze '87) </a>.



</section>

<section>
<h3> Other hard cases of $\PCON$  </h3>


<p class="fragment" 	data-fragment-index="1" align="left" >
<b> Theorem  <a href="" > (Kumar and Berman, to appear) </a></b>  $\PCON$  is $\PH$ for the following instances:

<ul>
<li class="fragment" 	data-fragment-index="2"> Uniform parents of robots with distinct radii
<li class="fragment" 	data-fragment-index="3"> General INID parents
</ul>




</section>


</section> <!-- Lower Bounds -->





</section> <!-- comm sim -->














